config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'


Rails.application.routes.draw do
  resources :favorites
  resources :clicks
  resources :messages
  resources :pictures
  devise_for :users


  mount Sidekiq::Web => '/admin/sidekiq'

  resources :pictures do
    resources :articles
  end

  resources :comments

  resources :articles do
    resources :pictures
    resources :clicks
    resources :comments
    member do
      put :traffic_up
      put :fav
    end

    collection do
      get :ascending
      get :descending
      get :time_order
    end

  end

  namespace 'admin' do
    resources :messages
  end

  resources :messages do
    member do
      put :checked
      put :unchecked
    end
  end

  resources :labels do
    member do
      put :live
      put :unlive
    end
  end

  resources :users, :path => "what"


  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  field :sender_id,    type: String
  field :content,   type: String
  field :status, type: Boolean, default: false

  def unread
    self.where(status: false).count
  end



end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :content)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :checked, :unchecked]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  def checked
    @message.update(status: true)
    redirect_to messages_path
  end

  def unchecked
    @message.update(status: false)
    redirect_to messages_path
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :content, :status)
    end
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>


  <div class="form-inputs">
    <% f.input :sender_id, label: "发送人" %>
    <% f.input :content, label: "内容" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h6>Editing Message</h6>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <td>发送人</td>
      <td>内容</td>
      <td>查看</td>
      <td>是否查看</td>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_id %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td>
          <% if message.status %>
            <%= link_to "未查看", unchecked_message_path(message), method: :put, class: "btn btn-default btn-xs" %>
          <% else%>
            <%= link_to "已查看", checked_message_path(message), method: :put, class: "btn btn-default btn-xs" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<%= simple_form_for @message do |f| %>


    <%= f.input :sender_id, label: "发送人" %>
    <%= f.input :content, label: "内容" %>


  <%= f.button :submit, "提 交", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <td>发件人</td>
      <td>内容</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @message.sender_id %></td>
      <td><%= @message.content %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>