config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'


Rails.application.routes.draw do
  resources :favorites
  resources :clicks
  resources :messages
  resources :pictures
  devise_for :users


  mount Sidekiq::Web => '/admin/sidekiq'

  resources :pictures do
    resources :articles
  end

  resources :comments

  resources :articles do
    resources :pictures
    resources :clicks
    resources :comments
    member do
      put :traffic_up
      put :fav
    end

    collection do
      get :ascending
      get :descending
      get :time_order
    end

  end

  namespace 'admin' do
    resources :messages
  end

  resources :messages do
    member do
      put :checked
      put :unchecked
    end
  end

  resources :labels do
    member do
      put :live
      put :unlive
    end
  end

  resources :users, :path => "what"


  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :avatar, AvatarUploader
  field :title, type: String
  field :content, type: String
  field :gonghao_name, type: String
  field :traffic, type: Integer, default: 0
  field :label, type: Boolean
  field :comments_count, type: Integer
  field :fav_count, type: Integer

  has_and_belongs_to_many :labels, autosave: true
  belongs_to :user, index: true
  has_and_belongs_to_many :pictures
  has_many :clicks
  embeds_many :comments
  has_many :favorites


  def traffic_add
    if self.clicks.create
      self.inc(traffic: 1)
      true
    end
  end

  def fav_add
    if self.favorites.create
      self.inc(favourites: 1)
      true
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @articles = Article.all
    @articles = @articles.order_by(traffic: params[:order_by_traffic]) unless params[:order_by_traffic].blank?
  end

  def show
    @article = Article.find(params[:id])
    @label = @article.labels
    @pictures = @article.pictures
    @picture = @article.pictures.new

    @comments = @article.comments
    @comment = @article.comments.new
    @comment = @article.favorites.new
  end


  def new
    @article = Article.new
    @labels = Label.all.map{|label| [label.name, label.id.to_s]}

  end

  def create
    @article = Article.new(article_params)
    selected_labels = Label.in(id: params["checked_labels"]&.values)
    puts "=" * 20
    puts selected_labels
    puts "-" * 20
    @article.labels << selected_labels
    if @article.save
      redirect_to articles_path
    else
      render :new
    end

  end

  def edit
    @article = Article.find(params[:id])
    @labels = Label.all.map{|label| [label.name, label.id.to_s]}
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:alert] = "Article deleted"
    redirect_to articles_path
  end

  def traffic_up
    @article = Article.find(params[:id])
    @article.traffic_add
    redirect_to article_path(@article)
  end

  def fav
    article = Article.find(params[:id])
    @current_user.fav(article)
    redirect_to article_path(article)
  end


  def ascending
    @articles = Article.all
    @articles = @articles.order_by(:traffic.asc)
    render :index
  end

  def descending
    @articles = Article.all
    @articles = @articles.order_by(:traffic.desc)
    render :index
  end

  def time_order
    @articles = Article.all
    @articles = @articles.order_by(created_at: :desc)
    render :index
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :gonghao_name, :traffic )
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<tr>
  <%= article.id %>
  <td><%= link_to(article.title, traffic_up_article_path(article), method: :put)%></td>
  <td><%= article.gonghao_name %></td>
  <td><%= article.traffic %></td>
  <td><%= article.comments.count %></td>
  <td><%= article.favorites.count %></td>
  <td><%= article.created_at.strftime("%F %T")%></td>
  <td><%= link_to('edit', edit_article_path(article), class: "btn btn-sm btn-default" ) %></td>
  <td><%= link_to('delete', article_path(article), class: "btn btn-sm btn-default",
              method: :delete, data: { confirm: "Are you sure?" } ) %></td>
</tr>

app/views/articles/edit.html.erb
<%= simple_form_for @article do |f| %>

<%= f.input :title, as: :string %>
<%= f.input :content, as: :text %>
<%= f.input :gonghao_name, as: :string %>

  <%= f.input :picture, as: :file %>
<% @labels.each_with_index do |label, index| %>
  <input id="" name="checked_labels[<%= index %>]" type="checkbox" value="<%= label[1] %>" <%= @article.labels.find(label[1]).nil? ? '' : 'checked' %> />
  <label for="pet_dog"><%= label[0] %></label>
<% end %>  </div>

<%= f.button :submit, "User Button Text", class: "my-button" %>
<% end %>

app/views/articles/index.html.erb
<div class="col-md-12">
  <div>
    <%= link_to("管理文章", articles_path, class: "btn btn-primary") %>

    <% if can? :read, Label %>
    <a href="/admin/sidekiq" class="auto">
      <i class="glyphicon glyphicon-stats icon text-primary"></i>
      <span class="font-bold">控制面板</span>
    </a>
      <%= link_to('管理标签', labels_path, class: "btn btn-primary") %>
      <%= link_to("管理图片", pictures_path, class: "btn btn-primary") %>

    <% end %>
    <% if can? :manage, User %>
      <%= link_to('管理用户', users_path, class: "btn btn-primary") %>
    <% end %>

  </div>
  <br>

    <table class="table table-hover">
        <thead>
          <tr>
            <td>标题</td>
            <td>来源</td>
            <td>
              阅读量排序
              <a href="/articles?order_by_traffic=desc">dd</a>
              <a href="/articles?order_by_traffic=asc">ff</a>

              <%= link_to("up", articles_path(order_by_traffic: :asc)) %>
              <%= link_to("down", articles_path(order_by_traffic: :desc)) %>
            </td>
            <td>评论数量</td>
            <td>收藏数量</td>
            <td>
              发表时间
              <%= link_to("time", time_order_articles_path) %>
            </td>

            <td>编辑</td>
            <td>删除</td>
          </tr>
        </thead>

        <tbody>
          <%= render(@articles) %>
        </tbody>
    </table>

</div>
<%= link_to("new文章", new_article_path, class: "btn btn-primary") %>

app/views/articles/new.html.erb
<%= simple_form_for @article do |f| %>

  <%= f.input :title, as: :string %>
  <%= f.input :content, as: :text %>
  <%= f.input :gonghao_name, as: :string %>


  <hr />



  <% @labels.each_with_index do |label, index| %>
    <input id="" name="checked_labels[<%= index %>]" type="checkbox" value="<%= label[1] %>" <%= @article.labels.find(label[1]).nil? ? '' : 'checked' %> />
    <label for="pet_dog"><%= label[0] %></label>
  <% end %>
  <%= f.button :submit, "提 交", class: "btn btn-primary" %>

<% end %>

app/views/articles/show.html.erb
<h4><%= link_to("收藏本文", fav_article_path(@article), method: :put) %></h4>


<table>
  <tr>
    <thead>
      <td>文章标题</td>
      <td>文章内容</td>
      <td>工号名字</td>
      <td>阅读量</td>
      <td>文章标签</td>

    </thead>
  </tr>
  <tr>
    <tbody>

      <td><%= @article.title %></td>
      <td><%= @article.content %></td>
      <td><%= @article.gonghao_name %></td>
      <td><%= @article.traffic %></td>
      <td>
        <% @article.labels.each do |label| %>
        <%= label.name %>
        <% end %>
      </td>
    </tbody>
  </tr>
</table>
<hr>

<h3>评论</h3>
<%= link_to("new comment", new_article_comment_path(@article)) %>


<h6>所有评论</h6>
<table>
  <thead>
    <tr>
      <td>评论者</td>

      <td>评论内容</td>

    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment|%>
    <tr>
      <td><%= comment.speaker_name %></td>

      <td><%= comment.text %></td>

    </tr>
    <% end %>
  </tbody>
</table>