config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'


Rails.application.routes.draw do
  resources :favorites
  resources :clicks
  resources :messages
  resources :pictures
  devise_for :users


  mount Sidekiq::Web => '/admin/sidekiq'

  resources :pictures do
    resources :articles
  end

  resources :comments

  resources :articles do
    resources :pictures
    resources :clicks
    resources :comments
    member do
      put :traffic_up
      put :fav
    end

    collection do
      get :ascending
      get :descending
      get :time_order
    end

  end

  namespace 'admin' do
    resources :messages
  end

  resources :messages do
    member do
      put :checked
      put :unchecked
    end
  end

  resources :labels do
    member do
      put :live
      put :unlive
    end
  end

  resources :users, :path => "what"


  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :role,               type: String
  field :username,           type: String
  field :active, type: Boolean, default: false

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ROLES = [:admin, :user, :collector]

  has_many :articles
  has_many :comments
  has_many :favorites


  def admin?
    role == 'admin'
  end

  def fav(article)
    self.favorites.create(article_title: article.title,
       username: self.email,
       article: article)
  end

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # @user = current_user
  end

  def sign
    if @user.daka
      flash[:notice] = "您已经打过卡了"
    else
      flash[:notice] = "恭喜您打卡成功"
    end
    redirect_to users_path(page: params[:page])
  end

  # def update_password
  #   @user = current_user
  #   if @user.update(user_params)
  #     bypass_sign_in(@user)
  #     redirect_to users_show_path
  #   else
  #     render "edit"
  #   end
  # end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def allow_without_password
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
          params[:user].delete(:password)
          params[:user].delete(:password_confirmation)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar,:role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { multipart: true, class: "form-horizontal" }) do |f| %>
  <%= f.input :email, label: "邮箱" %>
  <%= f.input :username, label: "用户名" %>

  <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %>
  <%= f.input :password, label: "密码" %>
  <%= f.input :password_confirmation, label: "确认密码" %>

  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= f.button :submit, "提 交", class: "btn btn-primary" %>
    <%= link_to "返 回", :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= user.score %></td>
  <td><%= link_to('edit', edit_user_path(user)) %></td>
  <td><%= link_to('delete', user_path(user), method: :delete) %></td>
</tr>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <td>用户名</td>
      <td>用户邮箱</td>
      <td>身份</td>
      <td>积分</td>
      <td>edit</td>
      <td>delete</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= render(@users) %>
    </tr>
  </tbody>
</table>

<%= link_to('新建用户', new_user_path(@user)) %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<tr>
  <td><%= @user.username %></td>
  <td><%= @user.email %></td>
  <td><%= @user.role %></td>
  <td><%= @user.score %></td>
  <td><%= link_to('edit', edit_user_path(@user)) %></td>
  <td><%= link_to('delete', user_path(@user), method: :delete) %></td>
</tr>