config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'


Rails.application.routes.draw do
  resources :favorites
  resources :clicks
  resources :messages
  resources :pictures
  devise_for :users


  mount Sidekiq::Web => '/admin/sidekiq'

  resources :pictures do
    resources :articles
  end

  resources :comments

  resources :articles do
    resources :pictures
    resources :clicks
    resources :comments
    member do
      put :traffic_up
      put :fav
    end

    collection do
      get :ascending
      get :descending
      get :time_order
    end

  end

  namespace 'admin' do
    resources :messages
  end

  resources :messages do
    member do
      put :checked
      put :unchecked
    end
  end

  resources :labels do
    member do
      put :live
      put :unlive
    end
  end

  resources :users, :path => "what"


  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  mount_uploader :avatar, AvatarUploader


  belongs_to :articles

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @article = Article.find(params[:article_id])

    @picture = @article.pictures.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to article_path(@article), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Article.find(params[:article_id]).pictures.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:avatar)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for(@picture) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>
  <%= f.input :avatar, as: :file %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Picture', new_picture_path %>
<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag picture.avatar.url('666') %></td>

        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<%= @picture.name %>
<%= image_tag @picture.avatar.url('666') %>